services:
  web:
    image: docker.io/zkeulr/duelgood-web:latest
    network_mode: host
    container_name: duelgood-web
    restart: unless-stopped
    volumes:
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: docker.io/zkeulr/duelgood-backend:latest
    network_mode: host
    container_name: duelgood-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/duelgood
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s # Give database time to initialize

  db:
    image: docker.io/library/postgres:15
    network_mode: host
    container_name: duelgood-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duelgood
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  nginx-logs:
    driver: local
  postgres_data:
    driver: local
