FROM docker.io/ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y postfix && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

COPY postfix/main.cf /etc/postfix/main.cf
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && \
    echo "duelgood.org" > /etc/mailname

EXPOSE 25

ENTRYPOINT ["/entrypoint.sh"]