FROM docker.io/mwader/postfix-relay:latest

# Install OpenDKIM
RUN apt-get update && \
    apt-get install -y opendkim opendkim-tools && \
    rm -rf /var/lib/apt/lists/*

# Copy configurations
COPY opendkim/opendkim.conf /etc/opendkim.conf
COPY opendkim/default /etc/default/opendkim
COPY entrypoint.sh /entrypoint.sh

RUN mkdir -p /etc/opendkim/keys/duelgood.org && \
    chown -R opendkim:opendkim /etc/opendkim && \
    chmod 700 /etc/opendkim/keys && \
    chmod +x /entrypoint.sh

# Create OpenDKIM directory
RUN mkdir -p /var/spool/postfix/opendkim && \
    chown opendkim:postfix /var/spool/postfix/opendkim && \
    chmod 750 /var/spool/postfix/opendkim

EXPOSE 25

ENTRYPOINT ["/entrypoint.sh"]